# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Obscured Narration
email: obscurednarration@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Opinions, reviews and general life evaluations through the lens of real people and the open-source community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: domcorriveau
github_username:  cinimodev

# Build settings
markdown: kramdown
remote_theme: "just-the-docs/just-the-docs"
plugins:
  - jekyll-feed
  - jekyll-include-cache
# Extra settings
# logo: "/assets/Logo-Video-Aspect-draft-mobo-cropped-20190103.png"
search_enabled: true
color_scheme: light

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-modernist

# Define Jekyll collections
collections:
  personal:
    permalink: "/:collection/:path/"
    output: true
  android:
    permalink: "/:collection/:path/"
    output: true
  desktop:
    permalink: "/:collection/:path/"
    output: true
  server:
    permalink: "/:collection/:path/"
    output: true
  general:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    personal:
      name: Personal News & Thoughts
      nav_exclude: false
      search_exclude: false
    android:
      name: Android
      nav_exclude: false
      search_exclude: false
    desktop:
      name: Linux Desktop
      nav_exclud: false
      search_exclude: false
    server:
      name: Linux Server
      nav_exclud: false
      search_exclude: false
    general:
      name: General Tech
      nav_exclud: false
      search_exclude: false
# Aux links for the upper right navigation
aux_links:
  "About Me":
    - "https://cinimodev.github.io/about/"
  "Marketing CV":
    - "https://cinimodev.github.io/marketing.html"
